# -*- coding: utf-8 -*-
"""basic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rdzFU-rHHEEi4x-7niQUnID9QyYal_1e
"""

l=[1,3,9]
l1=[1,3,9]
print(l+l1)

l1=[1,3,9]*3
print(l1)

l1=[1,3,9,"hello"]
print(l1[3])
print(l1[1:])
print(l1[:-1])

a=[1,2,3]
b=a[:]
print(b)



